name: SkRage
version: ${project.version}
main: com.akon.skrage.SkRage
author: akon
api-version: 1.12.2
depend: [Skript, ProtocolLib]
softdepend: [CrackShot, LibsDisguises, LunaChat, MythicMobs, MythicSkriptAddon]
